[package]
name = "ytmp3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
youtube_dl = "0.7.0"
futures = "0.3.5"
actix-web = "4"
